export const PHASE_REQUEST = 'PHASE_REQUEST';
export const PHASE = 'PHASE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FETCHING_REQUEST = 'CREATE_USER_FETCHING_REQUEST';
export const CREATE_USER_ERROR_REQUEST = 'CREATE_USER_ERROR_REQUEST';
export const CREATE_USER_RESPONSE_REQUEST = 'CREATE_USER_RESPONSE_REQUEST';

export const PHASE_QUESTION_ANS = 'PHASE_QUESTION_ANS';
export const PHASE_QUESTION_ANS_FETCHING_REQUEST = 'PHASE_QUESTION_ANS_FETCHING_REQUEST';
export const PHASE_QUESTION_ANS_ERROR_REQUEST = 'PHASE_QUESTION_ANS_ERROR_REQUEST';
export const PHASE_QUESTION_ANS_RESPONSE_REQUEST = 'PHASE_QUESTION_ANS_RESPONSE_REQUEST';

export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const CREATE_ACTIVITY_FETCHING_REQUEST = 'CREATE_ACTIVITY_FETCHING_REQUEST';
export const CREATE_ACTIVITY_ERROR_REQUEST = 'CREATE_ACTIVITY_ERROR_REQUEST';
export const CREATE_ACTIVITY_RESPONSE_REQUEST = 'CREATE_ACTIVITY_RESPONSE_REQUEST';

export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const UPDATE_ACTIVITY_FETCHING_REQUEST = 'UPDATE_ACTIVITY_FETCHING_REQUEST';
export const UPDATE_ACTIVITY_ERROR_REQUEST = 'UPDATE_ACTIVITY_ERROR_REQUEST';
export const UPDATE_ACTIVITY_RESPONSE_REQUEST = 'UPDATE_ACTIVITY_RESPONSE_REQUEST';

export const EMAIL_REPORT = 'EMAIL_REPORT';
export const EMAIL_REPORT_FETCHING_REQUEST = 'EMAIL_REPORT_FETCHING_REQUEST';
export const EMAIL_REPORT_ERROR_REQUEST = 'EMAIL_REPORT_ERROR_REQUEST';
export const EMAIL_REPORT_RESPONSE_REQUEST = 'EMAIL_REPORT_RESPONSE_REQUEST';

/** Messages **/
export const SERVER_ERROR_MSG = 'Something went wrong.';

/** Phase **/
export const MIN_PHASE = 1;
export const MAX_PHASE = 3;

/** Checkout Blog Link **/
export const BLOG_LINK = 'https://www.urability.com/blog';


